/**
 * Domain types for the virtual try-on module.
 *
 * These are shared by the browser, the route handlers and every provider
 * adapter, so nothing provider-specific may leak in here.
 */

export type GarmentLayer = 'feet' | 'bottom' | 'base' | 'mid' | 'outer' | 'head';

/** A single piece the shopper wants rendered onto the subject. */
export interface TryOnGarment {
  productId: string;
  name: string;
  /** Merchandising category, used for prompt phrasing ("a wool trench coat"). */
  category: string;
  layer: GarmentLayer;
  /** App-relative path or absolute URL to the garment's flat-lay image. */
  imageUrl: string;
  colorLabel?: string;
  size?: string;
}

/** The person (or demo figure) the garments are rendered onto. */
export interface TryOnSubject {
  kind: 'upload' | 'demo-model';
  /** `data:` URL. Uploads are downscaled in the browser before they get here. */
  dataUrl: string;
  width: number;
  height: number;
}

export interface TryOnRequest {
  subject: TryOnSubject;
  /** Ordered bottom-of-outfit first; the last entry sits on top. */
  garments: TryOnGarment[];
  /** Free-text styling direction shown to the shopper before it is sent. */
  notes?: string;
}

export type TryOnJobStatus = 'queued' | 'running' | 'succeeded' | 'failed' | 'cancelled';

export type TryOnErrorCode =
  | 'not_configured'
  | 'invalid_request'
  | 'unsupported_image'
  | 'rate_limited'
  | 'provider_error'
  | 'content_rejected'
  | 'timeout'
  | 'cancelled'
  | 'unknown';

export interface TryOnError {
  code: TryOnErrorCode;
  message: string;
  /** Whether the same request is worth sending again unchanged. */
  retryable: boolean;
}

export interface TryOnResult {
  /** Same-origin URL that streams the rendered image. */
  imageUrl: string;
  mimeType: string;
  /**
   * True when the image was composited locally rather than generated by an AI
   * model. The UI must label these — never present them as a real try-on.
   */
  simulated: boolean;
  provider: string;
  providerLabel: string;
  latencyMs: number;
  note?: string;
}

export interface TryOnJob {
  id: string;
  status: TryOnJobStatus;
  provider: string;
  providerLabel: string;
  /** 0..1, monotonic. Providers that cannot report real progress interpolate. */
  progress: number;
  /** Short shopper-facing message: "Reading your photo", "Draping the coat"… */
  stage: string;
  createdAt: number;
  updatedAt: number;
  garmentIds: string[];
  result?: TryOnResult;
  error?: TryOnError;
}

/** One way of connecting a real generation backend. */
export interface TryOnProviderOption {
  id: string;
  label: string;
  /** Environment variables this option needs, in the order to set them. */
  env: string[];
  /** Where the credential comes from. */
  credentialSource: string;
  note?: string;
}

/** What the storefront needs to know about the configured provider up front. */
export interface TryOnProviderInfo {
  id: string;
  label: string;
  /**
   * Whether the active provider has everything it needs. Note that the local
   * preview is "configured" yet still `simulated` — check both.
   */
  configured: boolean;
  /**
   * True when results are composited locally rather than generated by a model.
   * The UI must say so; a simulated result is never presented as an AI try-on.
   */
  simulated: boolean;
  /** Env vars that still need to be set, if any. */
  missing: string[];
  capabilities: TryOnCapabilities;
  notice?: string;
  /**
   * Present whenever no real model is generating — either nothing is connected
   * or the named provider is missing credentials. Lists what to set to fix it,
   * so the UI can name the provider and variables instead of failing vaguely.
   */
  setup?: {
    headline: string;
    detail: string;
    options: TryOnProviderOption[];
  };
}

export interface TryOnCapabilities {
  /** How many garments can be composed into one request. */
  maxGarments: number;
  /** Whether the provider keeps the original photo's background. */
  preservesBackground: boolean;
  /** Longest sensible wait before the job is abandoned. */
  timeoutMs: number;
  acceptedMimeTypes: string[];
  maxSubjectBytes: number;
}
