/**
 * Single source of truth for the demo catalogue.
 *
 * `npm run assets` reads this file to render the SVG artwork into
 * `public/demo/...` and to emit `src/data/catalog.generated.json`, which the
 * app consumes. Swapping in a real catalogue means replacing this file and the
 * artwork it points at — nothing in the UI hard-codes a product.
 */

export const CATEGORIES = [
  { id: 'all', label: 'All Categories' },
  { id: 'outerwear', label: 'Jackets & Outerwear' },
  { id: 'knitwear', label: 'Knitwear' },
  { id: 'tshirts', label: 'T-Shirts' },
  { id: 'hoodies', label: 'Hoodies & Sweatshirts' },
  { id: 'shirts', label: 'Shirts' },
  { id: 'trousers', label: 'Pants & Trousers' },
  { id: 'footwear', label: 'Shoes & Sneakers' },
  { id: 'accessories', label: 'Hats & Accessories' },
];

/** Where a garment sits when layered onto the figure. Higher wins. */
export const LAYERS = {
  base: 10,
  mid: 20,
  outer: 30,
  bottom: 5,
  feet: 1,
  head: 40,
};

const palettes = {
  camel: { light: '#d8b789', base: '#bb9463', dark: '#8a6a44', deep: '#6b5134', hardware: '#4a3a26', stitch: '#e4cba8' },
  army: { light: '#6e7b57', base: '#55603f', dark: '#3b442c', deep: '#2b311f', hardware: '#242a1b', stitch: '#8d9a73' },
  indigo: { light: '#7b93b4', base: '#5d789c', dark: '#3f566f', deep: '#2f4152', hardware: '#c9a227', stitch: '#e8d7a8' },
  olive: { light: '#7f8560', base: '#666b4a', dark: '#484c34', deep: '#353826', hardware: '#2c2f1f', stitch: '#9aa07a' },
  espresso: { light: '#61453a', base: '#4a332a', dark: '#31221c', deep: '#231814', hardware: '#b9b2a6', stitch: '#7a5c4e' },
  charcoal: { light: '#4a4e55', base: '#383c42', dark: '#26292e', deep: '#1c1f23', hardware: '#5c626b', stitch: '#5c626b' },
  chalk: { light: '#f5f2ec', base: '#e6e1d8', dark: '#c9c3b8', deep: '#b3ada2', hardware: '#a49d91', stitch: '#cfc9be' },
  oat: { light: '#ddceb4', base: '#c9b795', dark: '#a89876', deep: '#8b7d5f', hardware: '#7a6d52', stitch: '#e8dcc6' },
  slate: { light: '#5d6570', base: '#495059', dark: '#333940', deep: '#262b31', hardware: '#6f7883', stitch: '#79828d' },
  stone: { light: '#cfcabd', base: '#b8b2a3', dark: '#948e80', deep: '#787263', hardware: '#6b6557', stitch: '#ddd8cc' },
  ink: { light: '#2e3137', base: '#212429', dark: '#15171b', deep: '#0e1013', hardware: '#474b53', stitch: '#3d4149' },
  ecru: { light: '#ece5d6', base: '#dcd3bf', dark: '#bab098', deep: '#9d9380', hardware: '#8c8271', stitch: '#efe9dc' },
  optic: { light: '#fbfaf7', base: '#efece5', dark: '#d2cec4', deep: '#b7b2a7', hardware: '#8d8779', stitch: '#c4bfb4', sole: '#f7f5f0' },
  noir: { light: '#33363c', base: '#24272c', dark: '#16181c', deep: '#0d0f12', hardware: '#4b4f57', stitch: '#3b3f46' },
};

export const PRODUCTS = [
  // --- Photographed products -------------------------------------------------
  // These two carry real product photography from public/catalog/ rather than
  // generated artwork, so `shape` and `palette` are omitted. See docs/CATALOG.md.
  {
    id: 'navy-womens-tee',
    name: "Navy Women's T-Shirt",
    category: 'tshirts',
    image: '/catalog/navy-womens-tee.webp',
    price: 42,
    rating: 4.6,
    reviews: 214,
    layer: 'base',
    badge: 'new',
    fabric: 'Combed ring-spun cotton',
    care: 'Machine wash cold, tumble dry low',
    description:
      'A fitted crew-neck in deep navy, cut for a shorter body and a set-in sleeve. Holds its shape through the shoulder.',
    colors: [{ id: 'navy', label: 'Navy', hex: '#2f3d5c' }],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 'white-basic-tee',
    name: 'White Basic T-Shirt',
    category: 'tshirts',
    image: '/catalog/white-basic-tee.jpg',
    price: 28,
    rating: 4.4,
    reviews: 389,
    layer: 'base',
    badge: 'new',
    fabric: 'Heavyweight cotton jersey',
    care: 'Machine wash warm, tumble dry low',
    description:
      'The plain white crew, cut straight through the body with a ribbed collar and taped shoulders.',
    colors: [{ id: 'white', label: 'White', hex: '#f4f4f2' }],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },

  // --- Generated artwork -----------------------------------------------------
  {
    id: 'camel-wool-trench-coat',
    name: 'Camel Wool Trench Coat',
    category: 'outerwear',
    shape: 'trench-coat',
    palette: 'camel',
    price: 449,
    rating: 3.9,
    reviews: 128,
    layer: 'outer',
    badge: 'new',
    fabric: 'Double-faced wool, unlined',
    care: 'Dry clean only',
    description:
      'A long double-breasted trench cut from double-faced wool. Storm flap, belted waist and a drop shoulder that keeps the line soft.',
    colors: [
      { id: 'camel', label: 'Camel', hex: '#bb9463' },
      { id: 'ink', label: 'Ink', hex: '#24272c' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 'army-green-puffer-jacket',
    name: 'Army Green Puffer Jacket',
    category: 'outerwear',
    shape: 'puffer',
    palette: 'army',
    price: 189,
    compareAtPrice: 229,
    rating: 4.3,
    reviews: 412,
    layer: 'outer',
    badge: 'sale',
    fabric: 'Recycled ripstop, 700 fill',
    care: 'Machine wash cold, tumble dry low',
    description:
      'A lightweight down puffer with narrow quilting channels and a stand collar. Packs into its own pocket.',
    colors: [
      { id: 'army', label: 'Army', hex: '#55603f' },
      { id: 'noir', label: 'Noir', hex: '#24272c' },
      { id: 'stone', label: 'Stone', hex: '#b8b2a3' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'indigo-denim-trucker-jacket',
    name: 'Indigo Denim Trucker Jacket',
    category: 'outerwear',
    shape: 'denim-jacket',
    palette: 'indigo',
    price: 119,
    rating: 3.6,
    reviews: 96,
    layer: 'outer',
    badge: 'new',
    fabric: '13oz rigid selvedge denim',
    care: 'Wash sparingly, hang dry',
    description:
      'A rigid selvedge trucker with copper hardware and a boxy chest. Fades to your own shape over a season.',
    colors: [
      { id: 'indigo', label: 'Raw Indigo', hex: '#5d789c' },
      { id: 'ecru', label: 'Ecru', hex: '#dcd3bf' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 'olive-bomber-jacket',
    name: 'Olive Bomber Jacket',
    category: 'outerwear',
    shape: 'bomber',
    palette: 'olive',
    price: 159,
    rating: 4.4,
    reviews: 233,
    layer: 'outer',
    fabric: 'Cotton-nylon twill',
    care: 'Machine wash cold',
    description: 'A clean MA-1 silhouette with ribbed collar, cuffs and hem. Cut slightly cropped.',
    colors: [
      { id: 'olive', label: 'Olive', hex: '#666b4a' },
      { id: 'noir', label: 'Noir', hex: '#24272c' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'dark-brown-leather-biker-jacket',
    name: 'Dark Brown Leather Biker Jacket',
    category: 'outerwear',
    shape: 'biker',
    palette: 'espresso',
    price: 349,
    compareAtPrice: 429,
    rating: 3.8,
    reviews: 74,
    layer: 'outer',
    badge: 'sale',
    fabric: 'Vegetable-tanned lambskin',
    care: 'Leather conditioner only',
    description:
      'An asymmetric moto in vegetable-tanned lambskin. Belted hem, zipped cuffs, and a notch lapel that sits flat.',
    colors: [
      { id: 'espresso', label: 'Espresso', hex: '#4a332a' },
      { id: 'noir', label: 'Noir', hex: '#24272c' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
  },
  {
    id: 'charcoal-heavy-cotton-tee',
    name: 'Charcoal Heavy Cotton Tee',
    category: 'tshirts',
    shape: 'tee',
    palette: 'charcoal',
    price: 48,
    rating: 4.6,
    reviews: 619,
    layer: 'base',
    fabric: '240gsm combed cotton',
    care: 'Machine wash cold',
    description: 'A heavyweight tee with a ribbed neck that holds its shape. Boxy through the body.',
    colors: [
      { id: 'charcoal', label: 'Charcoal', hex: '#383c42' },
      { id: 'chalk', label: 'Chalk', hex: '#e6e1d8' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: 'off-white-boxy-tee',
    name: 'Off-White Boxy Tee',
    category: 'tshirts',
    shape: 'tee',
    palette: 'chalk',
    price: 48,
    rating: 4.2,
    reviews: 301,
    layer: 'base',
    fabric: '240gsm combed cotton',
    care: 'Machine wash cold',
    description: 'The same heavyweight body in undyed chalk. Wide shoulder, short sleeve.',
    colors: [
      { id: 'chalk', label: 'Chalk', hex: '#e6e1d8' },
      { id: 'oat', label: 'Oat', hex: '#c9b795' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 'oat-merino-crewneck',
    name: 'Oat Merino Crewneck',
    category: 'knitwear',
    shape: 'knit',
    palette: 'oat',
    price: 165,
    rating: 4.7,
    reviews: 188,
    layer: 'mid',
    badge: 'new',
    fabric: 'Extra-fine merino wool',
    care: 'Hand wash cold, dry flat',
    description: 'A fine-gauge merino crew knitted in one piece. Warm without bulk under a coat.',
    colors: [
      { id: 'oat', label: 'Oat', hex: '#c9b795' },
      { id: 'army', label: 'Army', hex: '#55603f' },
      { id: 'noir', label: 'Noir', hex: '#24272c' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 'slate-hooded-sweatshirt',
    name: 'Slate Hooded Sweatshirt',
    category: 'hoodies',
    shape: 'hoodie',
    palette: 'slate',
    price: 128,
    rating: 4.5,
    reviews: 402,
    layer: 'mid',
    fabric: '450gsm loopback cotton',
    care: 'Machine wash cold, dry flat',
    description: 'Loopback cotton, double-layer hood, kangaroo pocket. Heavy enough to wear on its own.',
    colors: [
      { id: 'slate', label: 'Slate', hex: '#495059' },
      { id: 'oat', label: 'Oat', hex: '#c9b795' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'stone-oxford-shirt',
    name: 'Stone Oxford Shirt',
    category: 'shirts',
    shape: 'shirt',
    palette: 'stone',
    price: 98,
    rating: 4.1,
    reviews: 143,
    layer: 'mid',
    fabric: 'Washed cotton oxford',
    care: 'Machine wash warm, iron damp',
    description: 'A washed oxford with a soft button-down collar and a single patch pocket.',
    colors: [
      { id: 'stone', label: 'Stone', hex: '#b8b2a3' },
      { id: 'indigo', label: 'Indigo', hex: '#5d789c' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 'black-tailored-trousers',
    name: 'Black Tailored Trousers',
    category: 'trousers',
    shape: 'trousers',
    palette: 'ink',
    price: 175,
    rating: 4.3,
    reviews: 167,
    layer: 'bottom',
    fabric: 'Tropical wool',
    care: 'Dry clean only',
    description: 'A pressed straight-leg in tropical wool. Sits at the natural waist, breaks once.',
    colors: [
      { id: 'ink', label: 'Ink', hex: '#212429' },
      { id: 'charcoal', label: 'Charcoal', hex: '#383c42' },
    ],
    sizes: ['28', '30', '32', '34', '36'],
  },
  {
    id: 'ecru-wide-leg-trousers',
    name: 'Ecru Wide-Leg Trousers',
    category: 'trousers',
    shape: 'trousers',
    palette: 'ecru',
    price: 145,
    compareAtPrice: 185,
    rating: 4.0,
    reviews: 88,
    layer: 'bottom',
    badge: 'sale',
    fabric: 'Heavy cotton drill',
    care: 'Machine wash cold',
    description: 'A wide, flat-fronted leg in heavy cotton drill. Falls straight from the hip.',
    colors: [
      { id: 'ecru', label: 'Ecru', hex: '#dcd3bf' },
      { id: 'olive', label: 'Olive', hex: '#666b4a' },
    ],
    sizes: ['28', '30', '32', '34', '36'],
  },
  {
    id: 'optic-leather-sneakers',
    name: 'Optic Leather Sneakers',
    category: 'footwear',
    shape: 'sneaker',
    palette: 'optic',
    price: 210,
    rating: 4.5,
    reviews: 274,
    layer: 'feet',
    badge: 'new',
    fabric: 'Full-grain leather, cupsole',
    care: 'Wipe clean',
    description: 'A low cupsole trainer in full-grain leather. Minimal panelling, no visible branding.',
    colors: [
      { id: 'optic', label: 'Optic', hex: '#efece5' },
      { id: 'noir', label: 'Noir', hex: '#24272c' },
    ],
    sizes: ['39', '40', '41', '42', '43', '44', '45'],
  },
  {
    id: 'noir-wool-flat-cap',
    name: 'Noir Wool Flat Cap',
    category: 'accessories',
    shape: 'cap',
    palette: 'noir',
    price: 85,
    rating: 4.2,
    reviews: 61,
    layer: 'head',
    fabric: 'Melton wool',
    care: 'Spot clean',
    description: 'A six-panel flat cap in melton wool with a short stitched brim.',
    colors: [
      { id: 'noir', label: 'Noir', hex: '#24272c' },
      { id: 'camel', label: 'Camel', hex: '#bb9463' },
    ],
    sizes: ['S/M', 'L/XL'],
  },
];

export function paletteFor(id) {
  const p = palettes[id];
  if (!p) throw new Error(`Unknown palette: ${id}`);
  return p;
}
