#!/usr/bin/env node
/**
 * Renders the demo catalogue artwork and emits the typed catalogue JSON.
 *
 *   npm run assets
 *
 * Output:
 *   public/demo/garments/<id>.svg        flat-lay product artwork
 *   public/demo/models/studio-figure.svg the default fitting-room figure
 *   src/data/catalog.generated.json      catalogue consumed by the app
 *
 * Assets are written to disk (not generated at request time) so the app serves
 * ordinary static files and a brand can drop real photography over them.
 */

import { existsSync } from 'node:fs';
import { mkdir, writeFile, rm } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { GARMENTS } from './lib/garments.mjs';
import { CATEGORIES, LAYERS, PRODUCTS, paletteFor } from './lib/manifest.mjs';
import { modelFigure } from './lib/model.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const garmentDir = join(root, 'public', 'demo', 'garments');
const modelDir = join(root, 'public', 'demo', 'models');
const dataDir = join(root, 'src', 'data');

async function main() {
  // Only the generated tree is cleared. public/catalog/ holds real
  // photography that this script must never touch.
  await rm(join(root, 'public', 'demo'), { recursive: true, force: true });
  await mkdir(garmentDir, { recursive: true });
  await mkdir(modelDir, { recursive: true });
  await mkdir(dataDir, { recursive: true });

  const catalog = [];

  for (const product of PRODUCTS) {
    const { shape, palette, image, ...rest } = product;

    // A product either carries real photography (`image`, a path under
    // public/) or is drawn from a parametric shape. Photographed products are
    // left alone — the generator never overwrites a file it did not create.
    let resolved = image;

    if (!resolved) {
      const draw = GARMENTS[shape];
      if (!draw) throw new Error(`No drawing for shape "${shape}" (${product.id})`);

      const file = `${product.id}.svg`;
      await writeFile(join(garmentDir, file), draw(paletteFor(palette)), 'utf8');
      resolved = `/demo/garments/${file}`;
    } else {
      const onDisk = join(root, 'public', resolved.replace(/^\//, ''));
      if (!existsSync(onDisk)) {
        throw new Error(`Missing product image for ${product.id}: public${resolved}`);
      }
    }

    catalog.push({
      ...rest,
      image: resolved,
      // Photography and generated artwork need different presentation: a cut-out
      // illustration sits directly on the dark card, a photo needs its own plate.
      media: image ? 'photo' : 'illustration',
      layerRank: LAYERS[product.layer],
    });
  }

  await writeFile(join(modelDir, 'studio-figure.svg'), modelFigure(), 'utf8');

  await writeFile(
    join(dataDir, 'catalog.generated.json'),
    `${JSON.stringify(
      {
        $comment: 'Generated by scripts/generate-assets.mjs — edit scripts/lib/manifest.mjs instead.',
        categories: CATEGORIES,
        defaultModel: '/demo/models/studio-figure.svg',
        products: catalog,
      },
      null,
      2,
    )}\n`,
    'utf8',
  );

  const drawn = catalog.filter((item) => item.image.startsWith('/demo/')).length;
  console.log(
    `Wrote ${drawn} drawn garments, referenced ${catalog.length - drawn} photographed, ` +
      '1 model figure, and catalog.generated.json',
  );
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
