#!/usr/bin/env node
/**
 * Renders the demo catalogue artwork and emits the typed catalogue JSON.
 *
 *   npm run assets
 *
 * Output:
 *   public/demo/garments/<id>.svg        flat-lay product artwork
 *   public/demo/models/studio-figure.svg the default fitting-room figure
 *   src/data/catalog.generated.json      catalogue consumed by the app
 *
 * Assets are written to disk (not generated at request time) so the app serves
 * ordinary static files and a brand can drop real photography over them.
 */

import { mkdir, writeFile, rm } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { GARMENTS } from './lib/garments.mjs';
import { CATEGORIES, LAYERS, PRODUCTS, paletteFor } from './lib/manifest.mjs';
import { modelFigure } from './lib/model.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const garmentDir = join(root, 'public', 'demo', 'garments');
const modelDir = join(root, 'public', 'demo', 'models');
const dataDir = join(root, 'src', 'data');

async function main() {
  await rm(join(root, 'public', 'demo'), { recursive: true, force: true });
  await mkdir(garmentDir, { recursive: true });
  await mkdir(modelDir, { recursive: true });
  await mkdir(dataDir, { recursive: true });

  const catalog = [];

  for (const product of PRODUCTS) {
    const draw = GARMENTS[product.shape];
    if (!draw) throw new Error(`No drawing for shape "${product.shape}" (${product.id})`);

    const svg = draw(paletteFor(product.palette));
    const file = `${product.id}.svg`;
    await writeFile(join(garmentDir, file), svg, 'utf8');

    const { shape: _shape, palette: _palette, ...rest } = product;
    catalog.push({
      ...rest,
      image: `/demo/garments/${file}`,
      layerRank: LAYERS[product.layer],
    });
  }

  await writeFile(join(modelDir, 'studio-figure.svg'), modelFigure(), 'utf8');

  await writeFile(
    join(dataDir, 'catalog.generated.json'),
    `${JSON.stringify(
      {
        $comment: 'Generated by scripts/generate-assets.mjs — edit scripts/lib/manifest.mjs instead.',
        categories: CATEGORIES,
        defaultModel: '/demo/models/studio-figure.svg',
        products: catalog,
      },
      null,
      2,
    )}\n`,
    'utf8',
  );

  console.log(`Wrote ${catalog.length} garments, 1 model figure, and catalog.generated.json`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
